s

diff --git a/aesd-char-driver/aesdchar_load b/aesd-char-driver/aesdchar_load
--- a/aesd-char-driver/aesdchar_load
+++ b/aesd-char-driver/aesdchar_load
@@ -12,19 +12,19 @@ else
 fi
 # cd /lib/modules/5.15.18/extra/
 # insmod ./lib/modules/5.15.18/extra/aesdchar.ko
-# if [ -e ${module}.ko ]; then
-#     echo "Loading local built file ${module}.ko"
-#     insmod ./$module.ko $* || exit 1
-# else
-echo "Local file ${module}.ko not found, attempting to modprobe"
-modprobe ${module} || exit 1
-# fi
+if [ -e ${module}.ko ]; then
+    echo "Loading local built file ${module}.ko"
+    insmod ./$module.ko $* || exit 1
+else
+    echo "Local file ${module}.ko not found, attempting to modprobe"
+    modprobe ${module} || exit 1
+fi
 echo "makenode"
 major=$(awk "\$2==\"aesdchar\" {print \$1}" /proc/devices) && \
-rm -f /dev/aesdchar && \
-mknod /dev/aesdchar c $major 0 && \
-chgrp $group /dev/aesdchar && \
-chmod $mode /dev/aesdchar
+sudo rm -f /dev/aesdchar && \
+sudo mknod /dev/aesdchar c $major 0 && \
+sudo chgrp $group /dev/aesdchar && \
+sudo chmod $mode /dev/aesdchar
 
 # major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
 # rm -f /dev/${device}
