com

diff --git a/aesd-char-driver/aesdchar_load b/aesd-char-driver/aesdchar_load
--- a/aesd-char-driver/aesdchar_load
+++ b/aesd-char-driver/aesdchar_load
@@ -10,15 +10,15 @@ if grep -q '^staff:' /etc/group; then
 else
     group="wheel"
 fi
-cd /lib/modules/5.15.18/extra/
+# cd /lib/modules/5.15.18/extra/
 # insmod ./lib/modules/5.15.18/extra/aesdchar.ko
-if [ -e ${module}.ko ]; then
-    echo "Loading local built file ${module}.ko"
-    insmod ./$module.ko $* || exit 1
-else
-    echo "Local file ${module}.ko not found, attempting to modprobe"
-    modprobe ${module} || exit 1
-fi
+# if [ -e ${module}.ko ]; then
+#     echo "Loading local built file ${module}.ko"
+#     insmod ./$module.ko $* || exit 1
+# else
+echo "Local file ${module}.ko not found, attempting to modprobe"
+modprobe ${module} || exit 1
+# fi
 major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
 rm -f /dev/${device}
 mknod /dev/${device} c $major 0
